version: "3.8"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: testpass
      PGDATA: /var/lib/postgresql/data/pgdat
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6381:6379

volumes:
  db:
